import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/view/navbar/page'
import Wrapper from './components/shared/wrapper/page'
import Footer from './components/view/footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
        <Navbar/>
        <div className='min-h-screen'>
        {children}
        </div>
        <Footer />
        </Wrapper>
        </body>
    </html>
  )
}
